search_trigger: ";;es;"
search_shortcut: Ctrl+Shift+Meta+j
preserve_clipboard: false

# backend: clipboard

# apply_patch: false
# disable_x11_fast_inject: true





# --[]-- [ ok ] ----
#
#
#
# # END--[]--- [ ok ] END----
# 




